version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile_local
    depends_on:
      - postgres
      - redis
    env_file:
      - backend/.env
    volumes:
      - .:/spotify-my-slack
    networks:
      - main
    ports:
      - 5000:5000
    init: true
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile_local
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
  postgres:
    image: postgres:12.1
    hostname: postgres
    environment:
      POSTGRES_DB: spotify_my_slack
    networks:
      - main
    restart: on-failure
networks:
  main:
