version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile_local
    depends_on:
      - postgres
      - redis
    env_file:
      - backend/.env
    volumes:
      - .:/spotify-my-slack
    networks:
      - main
    ports:
      - 5000:5000
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile_local
    volumes:
      - .:/spotify-my-slack
      - /spotify-my-slack/node_modules/
  postgres:
    image: postgres:10.10
    hostname: postgres
    environment:
      POSTGRES_DB: spotify_my_slack
      POSTGRES_USER: spotify_my_slack_user
      POSTGRES_PASSWORD: password
    networks:
      - main
    restart: on-failure
  redis:
    image: redis:5
    hostname: redis
    networks:
      - main
    restart: on-failure
networks:
  main:
