version: '3.7'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile_local
    depends_on:
      - postgres
    volumes:
      - "./src:/spotify-my-slack/src"
    networks:
      - main
    ports:
      - "5000:5000"
  postgres:
    image: postgres:10.7
    hostname: postgres
    environment:
      POSTGRES_DB: spotify_my_slack
      POSTGRES_USER: spotify_my_slack_user
      POSTGRES_PASSWORD: password
    networks:
      - main
    restart: on-failure
networks:
  main:
