name: test
on: push

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-test.txt
    - name: Lint with black
      run: black --check .
    - name: Lint with mypy
      run: mypy --config-file=mypy.ini backend
    - name: Lint with pylint
      run: pylint --rcfile=pylintrc backend

  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.13.1
    - run: npm install
      working-directory: frontend
    - run: npm run build
      working-directory: frontend
    - run: npm run lint
      working-directory: frontend
    - run: npm test
      working-directory: frontend
      env:
        CI: true
